# Generated by Django 4.1.7 on 2023-03-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Range',
            new_name='Type',
        ),
    ]
