# Generated by Django 4.1.7 on 2023-03-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
    ]
