# Generated by Django 4.1.7 on 2023-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_gallery_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Pname',
            new_name='Image_name',
        ),
    ]
