# Generated by Django 4.1.7 on 2023-03-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Computer Science', 'Computer Science')], max_length=20, null=True),
        ),
    ]
