# Generated by Django 4.1.7 on 2023-03-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ImageField(default='avatr.jpg', upload_to='Product_Images'),
        ),
    ]
