# Generated by Django 4.1.7 on 2023-03-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_product_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gallery',
            new_name='gallery1',
        ),
    ]
