# Generated by Django 4.1.7 on 2023-04-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_gallery_product_gallery1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='Image_name',
        ),
    ]
