# Generated by Django 4.1.5 on 2023-02-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addrerss',
            new_name='address',
        ),
    ]
